<?php

namespace AppBundle\Entity;

/**
 * DiscountCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
