<?php

namespace AppBundle\Entity;

/**
 * DiscountProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
