<?php

namespace AppBundle\Entity;

/**
 * DiscountProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountProductRepository extends \Doctrine\ORM\EntityRepository
{
}
