<?php

namespace AppBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducts(){
        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('p');
        $query = $qb
            ->andWhere($qb->expr()->isNotNull("p.quantity"))
            ->andWhere("p.quantity != 0")
            ->getQuery();


        return $query->getResult();

    }
}
