<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserVoteRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserVoteRepository extends EntityRepository
{
    public function insertVote(array $data){
        $vote = new UserVote();

        $vote->setProductId($data['product_id']);
        $vote->setUserId($data['user_id']);
        $vote->setRating($data['rating']);

        $em = $this->getEntityManager();
        $em->persist($vote);
        $em->flush();

        return $vote;
    }
}
