<?php

namespace AppBundle\Entity;

/**
 * UserRolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRolesRepository extends \Doctrine\ORM\EntityRepository
{
}
