user:
    path: /user
    defaults: { _controller: AppBundle:User:get }
    methods: [GET]
login:
    path: /login
    defaults: { _controller: AppBundle:Auth:login }
    methods: [POST]

logout:
    path: /logout
    defaults: { _controller: AppBundle:Auth:logout }
    methods: [POST]

register:
    path: /register
    defaults: { _controller: AppBundle:Auth:register }
    methods: [POST]

products:
    path: /products
    defaults: { _controller: AppBundle:Product:getProducts }
    methods: [GET]

product:
    path: /product/{id}
    defaults: { _controller: AppBundle:Product:getProduct }
    methods: [GET]

categories:
    path: /categories
    defaults: { _controller: AppBundle:Category:getCategories }
    methods: [GET]

category:
    path: /category/{id}
    defaults: { _controller: AppBundle:Category:getCategory }
    methods: [GET]
