<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll(){
        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('c');
        $query = $qb->where($qb->expr()->isNull('c.categoryId'))
                    ->getQuery();

        return $query->getResult();
    }

    public function getOneBy(array $by){
        $res = $this->findOneBy($by);
        $qb = $this->_em->createQueryBuilder()
                    ->select('p')
                   ->from('AppBundle:Product', 'p')
                   ->where('p.categoryId = :identifier')
                   ->setParameter('identifier', $by['id'])
                   ->getQuery();
        $res->setProducts($qb->getResult());

        return $res;
    }

}
